SELECT a.PRODUCT_ID, a.PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE YEAR(b.PRODUCE_DATE) = 2022 AND MONTH(b.PRODUCE_DATE) = 05
GROUP BY a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
