-- 코드를 입력하세요
SELECT AP.APNT_NO, P.PT_NAME, P.PT_NO, AP.MCDP_CD, D.DR_NAME, AP.APNT_YMD
FROM APPOINTMENT AP
JOIN PATIENT P ON AP.PT_NO = P.PT_NO
JOIN DOCTOR D ON AP.MDDR_ID = D.DR_ID
WHERE AP.MCDP_CD = 'CS' AND AP.APNT_YMD LIKE '2022-04-13%' AND AP.APNT_CNCL_YMD IS NULL
ORDER BY AP.APNT_YMD 