WITH FISH_MAX AS (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM 
        FISH_INFO
    WHERE 
        LENGTH IS NOT NULL
    GROUP BY 
        FISH_TYPE
),
MAX_FISH_INFO AS (
    SELECT 
        F.ID,
        F.FISH_TYPE,
        F.LENGTH
    FROM 
        FISH_INFO F
    JOIN 
        FISH_MAX M ON F.FISH_TYPE = M.FISH_TYPE AND F.LENGTH = M.MAX_LENGTH
)
SELECT 
    MFI.ID,
    FNI.FISH_NAME,
    MFI.LENGTH
FROM 
    MAX_FISH_INFO MFI
JOIN 
    FISH_NAME_INFO FNI ON MFI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY 
    MFI.ID ASC;
