name: Update README

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 5
      uses: actions/setup-python@v5
      with:
        python-version: 5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
    - name: Run update.py
      run: |
        python update.py
    - name: Commit changes
      run: |
        git config --global user.name 'chelsea7023'
        git config --global user.email 'yunhongkim123@gmail.com'
        git add -A
        git commit -am "auto update README.md"
    - name: Push changes
      run: |
        git push
